language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements-tests.txt
  - pip install coveralls
script:
  bash -c "coverage run --source pyradacctsrv `which trial` tests"
after_success:
  coveralls

